services:
  postgres:
    image: postgres:18.4
    container_name: postgres
    env_file:
      - .env
    environment:
      # postgres superuser db and credentials
      POSTGRES_DB: ${POSTGRES_DB_URL:-postgres}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
#      - promptvault-pgdata:/var/lib/postgresql
      - ./init-app-db.sh:/docker-entrypoint-initdb.d/init-app-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME:-promptvault} -d ${SPRING_DATASOURCE_URL:-promptvault}"]
      interval: 5s
      timeout: 5s
      retries: 10

